// swagger.mjs
import swaggerJsdoc from 'swagger-jsdoc';

// Swagger definition
const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: 'Express API with Swagger',
    version: '1.0.0',
    description: 'A sample API with autogenerated swagger doc',
  },
  servers: [
    {
      url: `http://localhost:${process.env.SERVER_PORT || 4000}`,
    },
    {
      url: `http://app.sprintly-exchange.com`,
    },
  ],
};

// Options for the swagger docs
const options = {
  swaggerDefinition,
  apis: ['./src/routes/**/*.mjs'], // Path to the API docs
};

// Initialize swagger-jsdoc
const swaggerSpec = swaggerJsdoc(options);

export default swaggerSpec;
